var master = [

{ quote: "SPARROWS ARE STUPID. THEY DONT GIVE A FUCK ABOUT ANYTHING"
	},

 { quote: "I MEAN, NO ONE WANTS TO ADMIT THAT THEY ATE 9 CANS OF RAVIOLI.. BUT..I DID. IM ASHAMED OF MYSELF"
	 },
 
 { quote: "SO ID LIKE TO MAKE A REQUEST UNDER THE PEOPLE’S FREEDOM OF CHOICES AND VOICES ACT THAT I BE ABLE TO SMOKE AND SWEAR IN YOUR COURTROOM"
	},

{ quote: "I NICKNAMED THIS ONE CROW SHERYL, AND SHES PRETTY COOL BUT I HAVE TO MAKE HER PEANUT BUTTER SANDWICHES SO SHE STOPS STEALING MY FUCKING DOPE!"
	},

{ quote:"I MEAN, I LOVE ALL CREATURES LIKE GOPHERS, AND DEERTS, AND.. THOSE THINGS THAT FLY… BUT FUCK SEAGULLS MAN, I GOT NO TIME FOR THOSE COCKSUCKERS!"
	},


 { quote: "THE FASTEST WAY TO GET MONEY IS TO STEAL IT FROM A BANK MACHINE, AND IT DOESNT TA ROCKET APPLIANCES TO REALIZE ALL YOU GOTTA DO IS TAKE A FUCKIN CHAIN, HOOK IT UP TO A TRUCK, AND YANK THE FUCKING BANK MACHINE OUTTA THE STORE"
	},

{ quote: "YOU CANT ARREST US, WERE STONED! WE CANT KNOW OUR RIGHTS"
	},

{ quote:"DO YOU WANT TO TAKE IT TO FUCKTOWN, LAHEY? CAUSE THATS WHERE THIS IS HEADED, DOWNTOWN FUCKTOWN!"
	},

{ quote: "IM NOT THE KIND OF PERSON TO SAY ATOADASO, BUT YA KNOW WHAT? ATOADASO, A-FUCKING-TOADASO"
	},

{ quote: "BREAKER BREAKER, COME IN EARTH, THIS IS ROCKET SHIP 27, ALIENS FUCKED OVER THE CARBONATOR ON ENGINE FOUR, IM GONNA TRY TO REFUCKULATE IT ON JUNIPER. UHH.. AND HOPEFULLY THEYVE GOT SOME, SPACE WEED THERE, OVER."
	},

{ quote: "I TRY TO BE A GOOD ROLE MODEL FOR KIDS AROUND THE PARK. IF SOME KID WANTS TO GROW DOPE, THEY CAN COME TALK TO ME INSTEAD OF GROWING DOPE 6 OR 7 TIMES THROUGH DENIAL AND ERROR, THEY’RE GOING TO GET IT RIGHT THE FIRST TIME AND HAVE SOME GOOD DOPE"
	}
];




var app = {
 getQuote: function() {
		var rand = Math.floor((Math.random() * (master.length)));
		return master[rand].quote;
		

	}
};

window.onload = console.log(app.getQuote());

		